### ISSUE TITLE
Question for you

### ISSUE THREAD

**Issue by kapteynpeter** [NJOYSoftware/git-updater#1]
Cool project! My question is what exactly is the use case for this? how does it improve upon the normal `git` workflow?

Thanks!

Peter

**Comment by NJOYSoftware** [comment]
Hi and thank you for the compliment!

This tool doesn't improve (directly) the normal `git` workflow: it aims to help users which cloned a repository to keep up to date with its remote reference.

Lets say you are really interested in [edex-ui](https://github.com/GitSquared/edex-ui) (just one of the first repo I found in trending as an example) but it doesn't have a package for your distribution and you need to compile it from source: with `git-updater` you can create an entry in your Gitfile in which you specify `tag: latest` to track the repository releases. Every time you execute `git-updater.exe apply <your Gitfile>`, if there is a new tag in edex-ui, your local copy of the repository will be bumped up to that new tag and, if specified, the install script will be executed.

Because of that, the usual git workflow is not interested, unless there is the need of cloning/updating another repository.

I hope this reply explains well the use case of this tool, english is not my first language :)
