### ISSUE TITLE
error output from git-updater apply

### ISSUE THREAD

**Issue by muralikodali** [NJOYSoftware/git-updater#2]
git-updater apply giving following error :  

dyaml.scanner.ScannerException@/home/alex/.dub/packages/dyaml-0.8.3/dyaml/source/dyaml/scanner.d(249): While scanning for the next token, found character '	', index 9 that cannot start any token
line 10,column 1
----------------
??:? @safe void dyaml.scanner.Scanner.fetchToken() [0x555f25feae75]
??:? @safe bool dyaml.scanner.Scanner.empty() [0x555f25fe9db4]
??:? @safe const(dyaml.token.Token) dyaml.scanner.Scanner.front() [0x555f25fe9d3c]
??:? @safe dyaml.event.Event dyaml.parser.Parser.parseBlockMappingKey!(0).parseBlockMappingKey() [0x555f25fe5732]
??:? @safe dyaml.node.Node dyaml.composer.Composer.composeNode(const(uint), const(uint)) [0x555f25ff4f4d]
??:? @safe dyaml.node.Node dyaml.composer.Composer.composeMappingNode(const(uint), const(uint)) [0x555f25ff63e9]
??:? @safe dyaml.node.Node dyaml.composer.Composer.composeNode(const(uint), const(uint)) [0x555f25ff5060]
??:? @safe dyaml.node.Node dyaml.composer.Composer.composeSequenceNode(const(uint), const(uint)) [0x555f25ff573f]
??:? @safe dyaml.node.Node dyaml.composer.Composer.composeNode(const(uint), const(uint)) [0x555f25ff5022]
??:? @safe dyaml.node.Node dyaml.composer.Composer.composeMappingNode(const(uint), const(uint)) [0x555f25ff63e9]
??:? @safe dyaml.node.Node dyaml.composer.Composer.composeNode(const(uint), const(uint)) [0x555f25ff5060]
??:? @safe dyaml.node.Node dyaml.composer.Composer.composeDocument() [0x555f25ff474f]
??:? @safe void dyaml.loader.Loader.popFront() [0x555f25fdf219]
??:? void file_parser.loadFile(const(immutable(char)[]), out file_option.RuntimeFileOption[], out repository.LocalRepository[]) [0x555f25f8aa77]
??:? void apply.apply(immutable(char)[]) [0x555f25fb7479]
??:? _Dmain [0x555f25fb6f40]

[config file](https://github.com/NJOYSoftware/git-updater/files/5504387/gitup.txt)

**Comment by NJOYSoftware** [comment]
Hi, the lines 10 and 11 of the given config file start with a tab (in my case it is equal to 2 spaces).
![VScode view](https://user-images.githubusercontent.com/14941985/98450996-1fccb680-2142-11eb-8576-c4ab202a7c25.png) 
From the image above, you can see that VScode recognizes and shows it as an arrow, while the spaces are shown as points (view image below).
![git-updater_#2_spaces](https://user-images.githubusercontent.com/14941985/98451036-720dd780-2142-11eb-963e-42661d9732b9.png)

I'd say that the yaml parser does not accept tabs to indent the lines of the config file (maybe because it can have a variable length), so I advise to change them to spaces.

Anyway, thanks for pointing it out, I'll add it to the readme so other users are aware of this!

Also, you made me find another bug (the check for options and repositories uniqueness was faulty), so I have to thank you also for this! ;)
